name: Jest Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  jest-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install modules
        run: npm ci
      - name: Start test server
        run: |
          npm run test:server &
          sleep 5
      - name: Test server response
        run: curl -I http://localhost:9999
      - name: Run Jest tests
        run: npm run test
